### ISSUE TITLE
seem that greentext_ssh doesn't quite work right

### ISSUE THREAD

**Issue by analogcity** [analogcity/utils#2]
Code in functions.sh more or less

content_ssh=$(/home/lowlife/bin/./ssh_postref "$content_ssh")
content_ssh=$(/home/lowlife/bin/./ssh_greentext "$content_ssh")
content_ssh=$(/home/lowlife/bin/./endline "$content_ssh")

When input is ">test\n\ntest" output should be "\\Z2\\Zb<br>test<br>test\\Zn" but it is "\\Z2\\Zb>testtest\\Zn"
@333-9

**Comment by analogcity** [comment]
Backslashes should be double I didn't know github filtered those

**Comment by 333-9** [comment]
shouldn't `endline` only edit html content?
the C code shouldn't replace newlines with nothing, may be something with bash.

**Comment by analogcity** [comment]
Well you see, if I save into the database the newline character, when I retract it and process it to gather the contents of the thread, it gets messed up and doesn't display properly. So I thought instead of saving the newline character why not save a marker for it and since I have this for HTML could work too for this scenario. This was my idea and probably is a shitty one but now it is set up like this. You can try to touch the script too if you want to fix the extracting of the database instead

**Comment by 333-9** [comment]
the only difference I can see in the output is that `\Zn` is printed after the last newline.
```
\Z2\Zb>multi
\Zn>line
\Z2\Zb>greentext
\Zn
```
mine does:
```
\Z2\Zb>multi\Zn
\Z2\Zb>line\Zn
\Z2\Zb>greentext\Zn
```

**Comment by 333-9** [comment]
changed the code from last time, so that newline.c only prints the `<br>`, but I don't know if that was the problem.

**Comment by analogcity** [comment]
Works like a charm now, thanks! And you are probably wright, I need to remake the bash scripts.

Make a pull request and I'll merge, again thanks!
